import { sql } from '@vercel/postgres';
import { create } from 'domain';
import { NextResponse } from 'next/server';
 
export async function GET(request: Request) {
  try {
    const create = `CREATE TABLE IF NOT EXISTS Accounts (
      aid integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      account_name varchar(255),
      account_number varchar(255) NOT NULL CHECK (account_number <> ''),
      createdtime timestamp DEFAULT current_timestamp,
      transaction_limit NUMERIC DEFAULT 0,
      balance_amount NUMERIC DEFAULT 0
       );`;
    const alter = `ALTER TABLE Accounts ADD CONSTRAINT constraint_unique_account_number UNIQUE (account_number);`;   
    // const result =
    //   await sql``;
  //   return NextResponse.json({ result }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error }, { status: 500 });
  }
}